SELECT H.NOM, H.PRENOM
FROM Humain H
JOIN Apparition A on H.NPERS = A.NPERS
JOIN Match M ON A.NMATH = M.NMATH
join Equipe E on H.NTEAM = E.NTEAM
WHERE M.RANG = 'Finale' AND A.ENTREE = 0 and E.CODE = 'FRA';

SELECT H.NOM, H.PRENOM, COUNT(CASE WHEN B.BUTEUR = H.NPERS THEN 1 END) as But, COUNT(CASE WHEN B.PASSEUR = H.NPERS THEN 1 END) as Passe
FROM Humain H
JOIN But B ON B.BUTEUR = H.NPERS OR B.PASSEUR = H.NPERS
JOIN Match M on M.NMATH = B.NMATH
WHERE M.RANG != 'Groupe' AND B.RANG != 'CSC'
GROUP BY H.NOM, H.PRENOM
HAVING COUNT(CASE WHEN B.BUTEUR = H.NPERS THEN 1 END) >= 1
   AND COUNT(CASE WHEN B.PASSEUR = H.NPERS THEN 1 END) >= 1
ORDER BY But DESC;

WITH counts AS (
  SELECT H.NOM, H.PRENOM, E.NOMEQ, COUNT(*) AS nB_Cartons,
         ROW_NUMBER() OVER (PARTITION BY H.NOM, H.PRENOM ORDER BY COUNT(*) DESC) AS rn
  FROM Humain H
  JOIN Arbitre A ON H.NPERS = A.NPRIN
  JOIN Match M ON M.NARBT = A.NARBT
  JOIN Carton C ON C.NMATH = M.NMATH
  JOIN Equipe E ON C.NTEAM = E.NTEAM
  GROUP BY H.NOM, H.PRENOM, E.NOMEQ
)
SELECT NOM, PRENOM, NOMEQ, nB_Cartons
FROM counts
WHERE rn = 1;
 
SELECT E.NOMEQ, 
       COUNT(CASE WHEN ((M.VAINQUEUR = 'Dom' AND M.NDOMI = E.NTEAM) OR (M.VAINQUEUR = 'Ext' AND M.NEXTE = E.NTEAM)) THEN 1 END) as Victoire, 
       COUNT(CASE WHEN M.VAINQUEUR = 'Nul' THEN 1 END) as Nul, 
       COUNT(CASE WHEN ((M.VAINQUEUR = 'Dom' AND M.NEXTE = E.NTEAM) OR (M.VAINQUEUR = 'Ext' AND M.NDOMI = E.NTEAM)) THEN 1 END) as Defaite,
       SUM(CASE WHEN M.NDOMI = E.NTEAM THEN split_part(M.RESULTAT, '-', 1)::int ELSE split_part(M.RESULTAT, '-', 2)::int END) as ButPour, 
       SUM(CASE WHEN M.NEXTE = E.NTEAM THEN split_part(M.RESULTAT, '-', 1)::int ELSE split_part(M.RESULTAT, '-', 2)::int END) as ButContre
FROM Equipe E
JOIN Match M on M.NDOMI = E.NTEAM OR M.NEXTE = E.NTEAM
GROUP by E.NOMEQ
ORDER BY Victoire DESC;